### ISSUE TITLE
./openvpn-ui: cannot execute: required file not found

### ISSUE THREAD

**Issue by vfdev-5** [d3vilh/openvpn-ui#63] opened 2024-04-21 00:05 UTC
Hi,

When trying to setup openvpn-server openvpn-ui together using [docker-compose-openvpnui.yml](https://github.com/d3vilh/openvpn-server/blob/main/docker-compose-openvpnui.yml), openvpn-ui service keeps restarting. Logs are showing:
```
Init. OVPN path: /etc/openvpn                                                                                                                    
Starting OpenVPN UI!                                                                                                                             
start.sh: line 33: ./openvpn-ui: cannot execute: required file not found   
```
What can be wrong in the configuration ? It would be good to get a better error message.

Another question, why we need `priviledged: true` option and mounting var docker volume for UI server?
Thanks!

**Comment by d3vilh** [comment] 2024-04-23 09:01
hi @vfdev-5,
Thank s for reporting.
Could you let me know which image you are using and what is the arch for your setup (`docker inspect --format='{{json .Config.Labels}}' d3vilh/openvpn-ui:latest` `uname -a`)?

The problem is `openvpn-ui` binary is not found when container attempt [to start it](https://github.com/d3vilh/openvpn-ui/blob/ab9dd379846e6cbe87ae36be456d2d87fb98ccf7/build/assets/start.sh#L33).

We need to mount `/var/docker` to be able to restart `openvpn` server container via UI.
**Privileged** is there just in case you have local openvpn-server with all the *privileged* permissions, for all other cases you could comment this line out.

**Comment by vfdev-5** [comment] 2024-04-23 09:38
Sure, I was using `d3vilh/openvpn-ui:0.9.5.1` (`{"maintainer":"Mr.Philipp <d3vilh@github.com>","version":"0.9.5.1"}`) image on raspberry pi 2 `(Linux rpi2 5.4.0-1069-raspi #79-Ubuntu SMP PREEMPT Thu Aug 18 18:18:46 UTC 2022 armv7l armv7l armv7l GNU/Linux)`. When I rebuild the image from source, it started working, hence the typo PR.

Thanks for explaining `/var/docker` and `privileged`, once I got into the UI I saw that it could restart openvpn server etc but before that just seeing docker-compose and UI part with high requirements like `/var/docker` and `privileged` were a bit surprising.

**Comment by d3vilh** [comment] 2024-04-23 11:42
OK, I know what the problem, let me build image for ARM71.
Ping you soon.

**Comment by d3vilh** [comment] 2024-04-23 12:32
Hey @vfdev-5 
Its ready. 

Delete current container and its image (`docker container rm openvpn-ui --force && docker image rm d3vilh/openvpn-ui --force`) then run it from the **docker-compose**(`docker-compose up -d`) again and it will pull new ARMv7 image.

Here is starting logs from my test server:
```logs
kit_v_kashkete@d3zero2-32:~/build/openvpn-server $ docker logs openvpn-ui
Init. OVPN path: /etc/openvpn
Starting OpenVPN UI!
Config file: conf/app.conf
...
2024/04/23 12:27:45.427 [I] [server.go:280]  http server Running on http://:8080
kit_v_kashkete@d3zero2-32:~/build/openvpn-server $ uname -a
Linux d3zero2-32 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux
kit_v_kashkete@d3zero2-32:~/build/openvpn-server $
```

**Comment by vfdev-5** [comment] 2024-04-23 13:15
Great, thanks a lot @d3vilh !

**Comment by d3vilh** [comment] 2024-05-06 15:05
Im closing this as resolved.

**Closed by d3vilh** 2024-05-06 15:05 UTC
Labels: help wanted, question, implemented
