### ISSUE TITLE
easy RSA vars, client/server default config files

### ISSUE THREAD

**Issue by reamasesa** [d3vilh/openvpn-ui#16] opened 2023-08-31 11:31 UTC
Hi,

Thank you for this neat project :)

1. I would like to set the easy-rsa defaults but no matter where I put the easy-rsa.vars and the vars files (config/pki directories), the UI shows the default ones that arrived with the container image

2. When creating a user configuration file from the UI, none of the easy RSA values from either ./config/easy-rsa.vars, ./config/vars or ./pki/vars are added to the certificate (it's the same with the server's certificate, only the CN field contains information)

3. Same with the server/client.conf files, unless I use the UI to change, f.e., the server's IP/FQDN, the files I placed in the "config" directory don't get used

4. I would also, if possible, ask for tags other than "latest" so I'll be able to use specific releases in my setup

I would like to automate this with my own values, perhaps I am using this tool(s) wrong and need some guidance

Thanks

**Comment by d3vilh** [comment] 2023-08-31 20:52
Hi @reamasesa,
Thank you for the feedback. 
> 1. conf/openvpn-server-config.tpl
> 2. When creating a user configuration file from the UI

I know this mess with easy-rsa vars I'm [currently working](https://github.com/d3vilh/openvpn-ui/tree/dev1) to fix it in next release by introducing two new tabs, so you can set vars with UI:
### EesyRSA vars
<img width="866" alt="Знімок екрана 2023-08-31 о 22 49 14" src="https://github.com/d3vilh/openvpn-ui/assets/33333559/5f281603-1327-409b-9e65-ba89a283e0a6">

### Maintenance
<img width="866" alt="Знімок екрана 2023-08-31 о 22 50 25" src="https://github.com/d3vilh/openvpn-ui/assets/33333559/01f476b4-6fae-43f9-88d5-3b36a56a7fa1">

The root cause of this mess is two different containers pointed to the same EasyRSA and PKI configuration. 
After the UI change I'll do a containers code cleanup and remove not necessary configuration files so, it will not confuse people anymore. In short main vars configuration file is `./pki/vars` and it is used during Certificate generation in the latest version.

> 3. Same with the server/client.conf files

UI and OpenVPN server both use the same server.conf file from `./openvpn/config/server.conf`. 
* UI have [own template](conf/openvpn-server-config.tpl) to save the configuration file by building it with vars/values you pass via Web interface, if youll add something there manually - next time when you'll press "Save" button in UI this changes will be lost. Again, I have an Idea to add "Custom configuration" input field in UI, so you can save there custom parameters.
* OpenVPN server itself don't track `./openvpn/config/server.conf` changes and just apply it during restart. Means as a crappy WA you can edit this file manually and never press "Save" button in UI 😎 Seriously, this needs to be fixed somehow.
 
Again, the `latest` aka `dev1` version have separate Client configuration page, so you can set address, port and port there and all new certificates will have this parameters inside:

<img width="845" alt="Знімок екрана 2023-08-31 о 23 02 52" src="https://github.com/d3vilh/openvpn-ui/assets/33333559/2fe8172f-1aba-4541-82de-852c409bf211">

> 4. I would also, if possible, ask for tags other than "latest" so I'll be able to use specific releases in my setup.

This is a TOP suggestion 😁 Literally the comment of the day.
I see more people are interesting in this project, so I'm changing release policy. Now and forever :current on Docker Hub and here will be linked to last [current release version](https://github.com/d3vilh/openvpn-ui/releases) on top of this I'll start using version tags on Docker Hub and here as well.

Now Current is [0.4 on Docker Hub](https://hub.docker.com/layers/d3vilh/openvpn-ui/0.4/images/sha256-2109c5a2af2fcb2801605e75686c900b732a7409f580b51d3d27823a1c8e84b1?context=repo) and [0.4 on GitHub](https://github.com/d3vilh/openvpn-ui/releases/tag/0.4) (I'll just drop it).

The development is [Dev on Docker Hub](https://hub.docker.com/layers/d3vilh/openvpn-ui/dev/images/sha256-4b617ed343e6ecd6a89e58b1627b09eff5a263579740acded284a022a1106ff0?context=repo) (there is only arm64 version) and [Dev* branch on GitHub](https://github.com/d3vilh/openvpn-ui/tree/dev1).

You can try Dev image from DockerHub it is pretty stable, but still did not tested with full scope.

**Comment by d3vilh** [comment] 2023-09-19 18:56
> I'd like to provide my own set of configuration files,

you can do it with version [`0.9`](https://github.com/d3vilh/openvpn-ui/releases/tag/0.9) its have completely redesigned Server and Client configuration templates approach, as well as option to customise configuration files.

**Comment by d3vilh** [comment] 2023-09-19 18:57
Closing this thread as "implemented" features. 
Were implemented in version [`0.9`](https://github.com/d3vilh/openvpn-ui/releases/tag/0.9).

**Closed by d3vilh** 2023-09-19 18:57 UTC
Labels: enhancement
